/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangPrivacyRouteImport } from './routes/$lang.privacy'
import { Route as LangDisclaimerRouteImport } from './routes/$lang.disclaimer'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangBooksRouteImport } from './routes/$lang.books'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangWarningsIndexRouteImport } from './routes/$lang.warnings.index'
import { Route as LangGenresIndexRouteImport } from './routes/$lang.genres.index'
import { Route as LangEndingsIndexRouteImport } from './routes/$lang.endings.index'
import { Route as LangCollectionsIndexRouteImport } from './routes/$lang.collections.index'
import { Route as LangAuthorsIndexRouteImport } from './routes/$lang.authors.index'
import { Route as LangWarningsCodeRouteImport } from './routes/$lang.warnings.$code'
import { Route as LangGenresSlugRouteImport } from './routes/$lang.genres.$slug'
import { Route as LangEndingsEndingRouteImport } from './routes/$lang.endings.$ending'
import { Route as LangCollectionsSlugRouteImport } from './routes/$lang.collections.$slug'
import { Route as LangBookSlugRouteImport } from './routes/$lang.book.$slug'
import { Route as LangAuthorsSlugRouteImport } from './routes/$lang.authors.$slug'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRoute,
} as any)
const LangDisclaimerRoute = LangDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangBooksRoute = LangBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangWarningsIndexRoute = LangWarningsIndexRouteImport.update({
  id: '/warnings/',
  path: '/warnings/',
  getParentRoute: () => LangRoute,
} as any)
const LangGenresIndexRoute = LangGenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => LangRoute,
} as any)
const LangEndingsIndexRoute = LangEndingsIndexRouteImport.update({
  id: '/endings/',
  path: '/endings/',
  getParentRoute: () => LangRoute,
} as any)
const LangCollectionsIndexRoute = LangCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthorsIndexRoute = LangAuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => LangRoute,
} as any)
const LangWarningsCodeRoute = LangWarningsCodeRouteImport.update({
  id: '/warnings/$code',
  path: '/warnings/$code',
  getParentRoute: () => LangRoute,
} as any)
const LangGenresSlugRoute = LangGenresSlugRouteImport.update({
  id: '/genres/$slug',
  path: '/genres/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangEndingsEndingRoute = LangEndingsEndingRouteImport.update({
  id: '/endings/$ending',
  path: '/endings/$ending',
  getParentRoute: () => LangRoute,
} as any)
const LangCollectionsSlugRoute = LangCollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangBookSlugRoute = LangBookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthorsSlugRoute = LangAuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/books': typeof LangBooksRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/disclaimer': typeof LangDisclaimerRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/authors/$slug': typeof LangAuthorsSlugRoute
  '/$lang/book/$slug': typeof LangBookSlugRoute
  '/$lang/collections/$slug': typeof LangCollectionsSlugRoute
  '/$lang/endings/$ending': typeof LangEndingsEndingRoute
  '/$lang/genres/$slug': typeof LangGenresSlugRoute
  '/$lang/warnings/$code': typeof LangWarningsCodeRoute
  '/$lang/authors/': typeof LangAuthorsIndexRoute
  '/$lang/collections/': typeof LangCollectionsIndexRoute
  '/$lang/endings/': typeof LangEndingsIndexRoute
  '/$lang/genres/': typeof LangGenresIndexRoute
  '/$lang/warnings/': typeof LangWarningsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/books': typeof LangBooksRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/disclaimer': typeof LangDisclaimerRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/authors/$slug': typeof LangAuthorsSlugRoute
  '/$lang/book/$slug': typeof LangBookSlugRoute
  '/$lang/collections/$slug': typeof LangCollectionsSlugRoute
  '/$lang/endings/$ending': typeof LangEndingsEndingRoute
  '/$lang/genres/$slug': typeof LangGenresSlugRoute
  '/$lang/warnings/$code': typeof LangWarningsCodeRoute
  '/$lang/authors': typeof LangAuthorsIndexRoute
  '/$lang/collections': typeof LangCollectionsIndexRoute
  '/$lang/endings': typeof LangEndingsIndexRoute
  '/$lang/genres': typeof LangGenresIndexRoute
  '/$lang/warnings': typeof LangWarningsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/books': typeof LangBooksRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/disclaimer': typeof LangDisclaimerRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/authors/$slug': typeof LangAuthorsSlugRoute
  '/$lang/book/$slug': typeof LangBookSlugRoute
  '/$lang/collections/$slug': typeof LangCollectionsSlugRoute
  '/$lang/endings/$ending': typeof LangEndingsEndingRoute
  '/$lang/genres/$slug': typeof LangGenresSlugRoute
  '/$lang/warnings/$code': typeof LangWarningsCodeRoute
  '/$lang/authors/': typeof LangAuthorsIndexRoute
  '/$lang/collections/': typeof LangCollectionsIndexRoute
  '/$lang/endings/': typeof LangEndingsIndexRoute
  '/$lang/genres/': typeof LangGenresIndexRoute
  '/$lang/warnings/': typeof LangWarningsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/books'
    | '/$lang/contact'
    | '/$lang/disclaimer'
    | '/$lang/privacy'
    | '/$lang/'
    | '/$lang/authors/$slug'
    | '/$lang/book/$slug'
    | '/$lang/collections/$slug'
    | '/$lang/endings/$ending'
    | '/$lang/genres/$slug'
    | '/$lang/warnings/$code'
    | '/$lang/authors/'
    | '/$lang/collections/'
    | '/$lang/endings/'
    | '/$lang/genres/'
    | '/$lang/warnings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/books'
    | '/$lang/contact'
    | '/$lang/disclaimer'
    | '/$lang/privacy'
    | '/$lang'
    | '/$lang/authors/$slug'
    | '/$lang/book/$slug'
    | '/$lang/collections/$slug'
    | '/$lang/endings/$ending'
    | '/$lang/genres/$slug'
    | '/$lang/warnings/$code'
    | '/$lang/authors'
    | '/$lang/collections'
    | '/$lang/endings'
    | '/$lang/genres'
    | '/$lang/warnings'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/books'
    | '/$lang/contact'
    | '/$lang/disclaimer'
    | '/$lang/privacy'
    | '/$lang/'
    | '/$lang/authors/$slug'
    | '/$lang/book/$slug'
    | '/$lang/collections/$slug'
    | '/$lang/endings/$ending'
    | '/$lang/genres/$slug'
    | '/$lang/warnings/$code'
    | '/$lang/authors/'
    | '/$lang/collections/'
    | '/$lang/endings/'
    | '/$lang/genres/'
    | '/$lang/warnings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/disclaimer': {
      id: '/$lang/disclaimer'
      path: '/disclaimer'
      fullPath: '/$lang/disclaimer'
      preLoaderRoute: typeof LangDisclaimerRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/books': {
      id: '/$lang/books'
      path: '/books'
      fullPath: '/$lang/books'
      preLoaderRoute: typeof LangBooksRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/warnings/': {
      id: '/$lang/warnings/'
      path: '/warnings'
      fullPath: '/$lang/warnings/'
      preLoaderRoute: typeof LangWarningsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/genres/': {
      id: '/$lang/genres/'
      path: '/genres'
      fullPath: '/$lang/genres/'
      preLoaderRoute: typeof LangGenresIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/endings/': {
      id: '/$lang/endings/'
      path: '/endings'
      fullPath: '/$lang/endings/'
      preLoaderRoute: typeof LangEndingsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/collections/': {
      id: '/$lang/collections/'
      path: '/collections'
      fullPath: '/$lang/collections/'
      preLoaderRoute: typeof LangCollectionsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/authors/': {
      id: '/$lang/authors/'
      path: '/authors'
      fullPath: '/$lang/authors/'
      preLoaderRoute: typeof LangAuthorsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/warnings/$code': {
      id: '/$lang/warnings/$code'
      path: '/warnings/$code'
      fullPath: '/$lang/warnings/$code'
      preLoaderRoute: typeof LangWarningsCodeRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/genres/$slug': {
      id: '/$lang/genres/$slug'
      path: '/genres/$slug'
      fullPath: '/$lang/genres/$slug'
      preLoaderRoute: typeof LangGenresSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/endings/$ending': {
      id: '/$lang/endings/$ending'
      path: '/endings/$ending'
      fullPath: '/$lang/endings/$ending'
      preLoaderRoute: typeof LangEndingsEndingRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/collections/$slug': {
      id: '/$lang/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/$lang/collections/$slug'
      preLoaderRoute: typeof LangCollectionsSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/book/$slug': {
      id: '/$lang/book/$slug'
      path: '/book/$slug'
      fullPath: '/$lang/book/$slug'
      preLoaderRoute: typeof LangBookSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/authors/$slug': {
      id: '/$lang/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/$lang/authors/$slug'
      preLoaderRoute: typeof LangAuthorsSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangBooksRoute: typeof LangBooksRoute
  LangContactRoute: typeof LangContactRoute
  LangDisclaimerRoute: typeof LangDisclaimerRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangIndexRoute: typeof LangIndexRoute
  LangAuthorsSlugRoute: typeof LangAuthorsSlugRoute
  LangBookSlugRoute: typeof LangBookSlugRoute
  LangCollectionsSlugRoute: typeof LangCollectionsSlugRoute
  LangEndingsEndingRoute: typeof LangEndingsEndingRoute
  LangGenresSlugRoute: typeof LangGenresSlugRoute
  LangWarningsCodeRoute: typeof LangWarningsCodeRoute
  LangAuthorsIndexRoute: typeof LangAuthorsIndexRoute
  LangCollectionsIndexRoute: typeof LangCollectionsIndexRoute
  LangEndingsIndexRoute: typeof LangEndingsIndexRoute
  LangGenresIndexRoute: typeof LangGenresIndexRoute
  LangWarningsIndexRoute: typeof LangWarningsIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangBooksRoute: LangBooksRoute,
  LangContactRoute: LangContactRoute,
  LangDisclaimerRoute: LangDisclaimerRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangIndexRoute: LangIndexRoute,
  LangAuthorsSlugRoute: LangAuthorsSlugRoute,
  LangBookSlugRoute: LangBookSlugRoute,
  LangCollectionsSlugRoute: LangCollectionsSlugRoute,
  LangEndingsEndingRoute: LangEndingsEndingRoute,
  LangGenresSlugRoute: LangGenresSlugRoute,
  LangWarningsCodeRoute: LangWarningsCodeRoute,
  LangAuthorsIndexRoute: LangAuthorsIndexRoute,
  LangCollectionsIndexRoute: LangCollectionsIndexRoute,
  LangEndingsIndexRoute: LangEndingsIndexRoute,
  LangGenresIndexRoute: LangGenresIndexRoute,
  LangWarningsIndexRoute: LangWarningsIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
