/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangBooksRouteImport } from './routes/$lang.books'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangBookSlugRouteImport } from './routes/$lang.book.$slug'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangBooksRoute = LangBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangBookSlugRoute = LangBookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/books': typeof LangBooksRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/book/$slug': typeof LangBookSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/books': typeof LangBooksRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/book/$slug': typeof LangBookSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/books': typeof LangBooksRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/book/$slug': typeof LangBookSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/books'
    | '/$lang/'
    | '/$lang/book/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$lang/about' | '/$lang/books' | '/$lang' | '/$lang/book/$slug'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/books'
    | '/$lang/'
    | '/$lang/book/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/books': {
      id: '/$lang/books'
      path: '/books'
      fullPath: '/$lang/books'
      preLoaderRoute: typeof LangBooksRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/book/$slug': {
      id: '/$lang/book/$slug'
      path: '/book/$slug'
      fullPath: '/$lang/book/$slug'
      preLoaderRoute: typeof LangBookSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangBooksRoute: typeof LangBooksRoute
  LangIndexRoute: typeof LangIndexRoute
  LangBookSlugRoute: typeof LangBookSlugRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangBooksRoute: LangBooksRoute,
  LangIndexRoute: LangIndexRoute,
  LangBookSlugRoute: LangBookSlugRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
